super_lio_bridge:
  ros__parameters:
    odom_input_topic: "/lio/odom"
    cloud_input_topic: "/lio/cloud_world"

    state_output_topic: "/state_estimation"
    cloud_output_topic: "/registered_scan"

    global_frame: "world"
    child_frame: "imu"

    publish_tf: false
