name: work_odin1

x-env-files: &env-files
  - ${ENV_DIR}/ros2.env
  - ${ENV_DIR}/timezone.env
  - ${ENV_DIR}/ywz/runtime.env

services:

  odin1:
    image: nav_gui_snapshot:20260813
    container_name: odin1

    network_mode: host
    ipc: host

    # ################################
    # Docker: bind Odin1 data transport to CPU 0
    # ################################
    cpuset: "6"

    privileged: true

    ulimits:
      core: 0

    env_file: *env-files

    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /root/.Xauthority
      QT_X11_NO_MITSHM: "1"

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/siasun/.Xauthority:/root/.Xauthority:ro

      - /dev:/dev:rw

      - ${ENV_DIR}/ros2/:/root/env/ros2:ro

      # ################################
      # Docker: mount LQP workspace
      # ################################
      - /home/siasun/panda3_2026_07_17/panda3/src/lqp:/root/work/lqp:rw

    working_dir: /root/work/lqp

    stdin_open: true
    tty: true

    restart: unless-stopped

    command:
      - bash
      - -lc
      - |
        set -e

        apt-get update

        DEBIAN_FRONTEND=noninteractive apt-get install -y \
          x11-apps \
          usbutils

        source /opt/ros/humble/setup.bash

        echo "======================================"
        echo " Odin1 container started"
        echo " CPU affinity: 0"
        echo " Workspace: /root/work/lqp"
        echo "======================================"

        taskset -cp $$ || true

        exec bash
